### ISSUE TITLE
Use of PAMLr with Migrate Tech data

### ISSUE THREAD

**Issue by FraserFlycatcher** [KiranLDA/PAMLr#2]
Hi Kiran and team, can the package support migrate tech logger data (.lux, .deg)?

**Comment by KiranLDA** [comment]
Hi @FraserFlycatcher, it doesn't explicitly include migrate tech, as I have not had access to the raw data or the time to update the package. 

However, I have some code to work around it:

pathname = “path/where/both/files/stored/” # this is assuming each individual is kept in it’s own folders

dta=list()
dta$id = "PutIDCodeHere"

#import light
light = read.delim(list.files(pathname,pattern=".lux",full.names = TRUE)[1],skip=20,sep="",header = FALSE)
light = as.data.frame(list(date=as.POSIXct(strptime(paste(light[,1],light[,2]),
                                                    tz="UTC",format="%d/%m/%Y %H:%M:%S")),obs=light[,3]))
dta$light = light

#import temperature
temperature = read.delim(list.files(pathname,pattern=".deg",full.names = TRUE),skip=20,sep="",header = FALSE)
temperature = as.data.frame(list(date=as.POSIXct(strptime(paste(temperature[,1],temperature[,2]),
                                                          tz="UTC",format="%d/%m/%Y %H:%M:%S")),obs=temperature[,3]))
dta$temperature = temperature

#import pressure
pressure = read.delim(list.files(pathname,pattern=".deg",full.names = TRUE),skip=20,sep="",header = FALSE)
pressure = as.data.frame(list(date=as.POSIXct(strptime(paste(pressure[,1],pressure[,2]),
                                                          tz="UTC",format="%d/%m/%Y %H:%M:%S")),obs=pressure[,4]))
dta$pressure = pressure


#this is just to rename it so it works with examples in the user manual
PAM_data=dta

#plot it
plot_interactive_timeseries( PAM_data)
